name: Build MAUI Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  build-android:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore PresentacionMAUI.csproj
      
    - name: Build and Publish Android
      run: |
        dotnet publish PresentacionMAUI.csproj -f net8.0-android -c Release -p:AndroidPackageFormat=apk -p:PublishTrimmed=true
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TarjetaVirtual-APK
        path: |
          **/publish/*.apk
        retention-days: 30
